### ISSUE TITLE
Evaluate compatibility of Youth Network and The Monitor data with our schema. 

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/open-data#1]
How much of the data in these databases is compatible with our data?
The Monitor
www.monitor.coop
Mapping of youth coops at 
http://umap.openstreetmap.fr/en/map/ica-youth-network_307192#2/12.9/4.0

**Comment by ColmMassey** [comment]
Latest data from youth co-ops is here.

**Comment by ColmMassey** [comment]
Hi @dtmakm27. Have you had a chance to look at what it would take to spin up a map with the basic Youth Co-op data?

**Comment by dtmakm27** [comment]
Do the files in the nextcloud /ica folder describe the same data?

**Comment by dtmakm27** [comment]
We have to add unique identification for each (which would be just numbering them from 1 - n)
Change some field names that don't make sense
Work out how to parse the address as it does not have any format

And then it's do-able

**Comment by ColmMassey** [comment]
> Do the files in the nextcloud /ica folder describe the same data?

Yes, this one. Youth-led Co-ops - Coops_new.csv. It was downloaded 2 weeks ago, so perhaps a little old, but fine to run a test on.

**Comment by ColmMassey** [comment]
> We have to add unique identification for each (which would be just numbering them from 1 - n)

Fine for test.

>Change some field names that don't make sense
Yes. I'll take a look at how to disentangle what _name_, with lowercase 'n', _Sector_ and _Type_ would map to in our schema. 

>address might be the one that is not so straight forward

Given we have long and lat provided, first draft could just put the entire address into one field.
Later we could see if they are colllecting the data further up the chain in a more structured way, or we can use a geo tool to split them out into subfields.

**Comment by ColmMassey** [comment]
>_name_, with lowercase 'n', 

is safe to ignore.

**Comment by ColmMassey** [comment]
Creating Issue to implement Youth network database and map here
https://github.com/SolidarityEconomyAssociation/open-data/issues/11 and
https://github.com/SolidarityEconomyAssociation/sea-map/issues/30

**Comment by ColmMassey** [comment]
New issue to publish Monitor data [here](https://github.com/SolidarityEconomyAssociation/open-data/issues/12)
