### ISSUE TITLE
Republish latest Co-ops UK data.

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/open-data#16]
2020 Q1 Data has been published. Check that issues referenced in https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/215
have been resolved once this data is publihsed.

**Comment by dtmakm27** [comment]
But not sure why you are looking at dotcooptest. It is way old.

I think need to remove the old confusing graphs.
