### ISSUE TITLE
Broken converting the data link in documentation 

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/open-data#18]
At https://github.com/SolidarityEconomyAssociation/open-data#converting-the-data

Where should https://github.com/SolidarityEconomyAssociation/open-data/blob/master/tools/se_open_data/csv/standard.rb point to now?

**Comment by wu-lee** [comment]
It should point here:

https://github.com/SolidarityEconomyAssociation/open-data/blob/master/tools/se_open_data/lib/se_open_data/csv/standard.rb

I've just fixed it.
