### ISSUE TITLE
ESSGlobal Vocab extensions

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/open-data#20]
We need to add the following categories in order to support the ICA/ILO categorisations.

Agriculture, 
Industry, 
Utilities
& Transport to 
Economic Activities/Sectors (Modified) VES

And 

Mutual, 
National apex, 
National sectoral federation or union,
Regional, state or provincial level federation or union,
Cooperative group,
Government agency/body
to Organisational Structure VES

**Comment by ColmMassey** [comment]
And demonstrate their use by extending ICA data importer to support.

**Comment by ColmMassey** [comment]
Can we see if there is an existing schema that would work for the ICA's Regions & SuperRegions?

**Comment by dtmakm27** [comment]
Installing rapper could be a bit of a hassle in the future for others so i'm putting in the related info here:
http://librdf.org/raptor/INSTALL.html  -- link for raptor package (includes rapper)

https://github.com/timrdf/prizms/issues/87 (fix the configure bug for missing library)

https://github.com/ruby-rdf/rdf-raptor/issues/20 (fix for
rapper: error while loading shared libraries: libraptor2.so.0: cannot open shared object file: No such file or directory
)

**Comment by dtmakm27** [comment]
https://github.com/essglobal-linked-open-data/map-sse

This is the repo that the https://vocabs.solidarityeconomy.coop/essglobal/V2a/vocab-content/essglobal-vocab.html is based on and contains the most recent code

**Comment by dtmakm27** [comment]
BTW @ColmMassey what was the thought behind making a seperate modified definition? (i.e. Economic Activities/Sectors (Modified) VES) instead of just adding to the old one?

**Comment by dtmakm27** [comment]
Note: 

<http://purl.org/essglobal/vocab/economicSector>
  rdfs:label "Economic Sector"@en ;
  rdfs:label "Setor Económico"@pt ;
  dc:description "A categorization of the type of activities carried on by SSE initiatives."@en ;
  dc:description "Categorização do tipo de atividades exercidas por iniciativas da ESS."@pt ;
  rdfs:isDefinedBy <http://purl.org/essglobal/vocab/> ;
  dc:issued "2014-02-06"^^xsd:date ;
  dc:modified "2019-05-28"^^xsd:date ;
  a owl:DatatypeProperty ;
  rdfs:range <http://purl.org/essglobal/vocab/ActivitiesModified> ;  
  rdfs:domain <http://purl.org/essglobal/vocab/SSEInitiative> .

<http://purl.org/essglobal/vocab/primarySector>
  rdfs:label "Primary Sector"@en ;
  dc:description "The primary activity carried out by SSE initiatives."@en ;
  rdfs:isDefinedBy <http://purl.org/essglobal/vocab/> ;
  dc:issued "2019-05-20"^^xsd:date ;
  dc:modified "2019-05-20"^^xsd:date ;
  a owl:DatatypeProperty ;
  rdfs:range <http://purl.org/essglobal/vocab/ActivitiesModified> ;  
  rdfs:domain <http://purl.org/essglobal/vocab/SSEInitiative> .


This could be potentially incorrect, the range should include both concepts of http://purl.org/essglobal/vocab/ActivitiesModified and http://purl.org/essglobal/vocab/Activities

**Comment by ColmMassey** [comment]
> BTW @ColmMassey what was the thought behind making a seperate modified definition? (i.e. Economic Activities/Sectors (Modified) VES) instead of just adding to the old one?

When we were presenting the original list of activities to people, it was felt that it was too long a list and wasn't useful for groups todescribe what they did. So the team (I wasn't part of this) created a new list. This is big open ended issue.

**Comment by ColmMassey** [comment]
> And do you have any idea why the html/rdf is not generated from the ttl and skos?

I don't know anything about how they are generated. Soz.

**Comment by ColmMassey** [comment]
> This could be potentially incorrect, the range should include both concepts of http://purl.org/essglobal/vocab/ActivitiesModified and http://purl.org/essglobal/vocab/Activities

Would be good to discuss this. next week.

**Comment by dtmakm27** [comment]
Ah, just had a sudden realisation... 

I added the activities and generated the dictionary, seems to be working perfectly fine, I just need to upload and make the swap in the rdf converter for the ICA data. 

BUT 

My previous comment describes a potential error in the ontology. If we fix (the perceived) error we can just use the existing ontology definitions (e.g. https://vocabs.solidarityeconomy.coop/essglobal/V2a/html-content/essglobal.html#activities-A08) instead of creating new ones. 
But then again. I will just extend the definition for now and we can open up a different ticket in the future for changing the ontology

**Comment by dtmakm27** [comment]
It seems like the added term for:

https://w3id.solidarityeconomy.coop/essglobal/V2a/standard/organisational-structure/OS115

is not commited to the vocabulary repo: https://github.com/essglobal-linked-open-data/map-sse/tree/extension-test

I guess the latest commit there should have included it but something glitched a bit with git? @joebillings 
https://github.com/essglobal-linked-open-data/map-sse/commit/94a21064f7fea1addff9dcf3029f105fc083560e

I will add it in with some additional fixes to the repo

**Comment by dtmakm27** [comment]
@ColmMassey updated and made a couple of changes as well 

Added the terms 
Updated dates 
fixed anchoring bug for AM 
Fixed name of OS100
Commited uncommited changes to repository (I need access)
+some minor fixes to the html

I also updated the mapping for the sausage factory
We need to update the mapping for activities/organisation structures in the maps as well

**Comment by dtmakm27** [comment]
Updated the map as well: http://dev.ica.solidarityeconomy.coop/

Shall we close this?

**Comment by ColmMassey** [comment]
> We need to update the mapping for activities/organisation structures in the maps as well

Does this warrant anew Issue and then we close this one?

**Comment by ColmMassey** [comment]
>Updated the map as well: http://dev.ica.solidarityeconomy.coop/
What do you mean by this? The org types all seem to be displayed as undefined. Activities not displayed yet. Did you mean something else?

**Comment by dtmakm27** [comment]
@ColmMassey Apologies, I updated the map only locally and forgot to deploy.
Should be good now: https://dev.ica.solidarityeconomy.coop/

**Comment by ColmMassey** [comment]
Would you still expect some of them to be undefined, like
https://data1.solidarityeconomy.coop/ICA/42.html

**Comment by ColmMassey** [comment]
> Would you still expect some of them to be undefined, like
> https://data1.solidarityeconomy.coop/ICA/42.html

Scratch that. It hadn't refreshed, for some reason. The undefined are gone!

**Comment by dtmakm27** [comment]
> Can we see if there is an existing schema that would work for the ICA's Regions & SuperRegions?


https://en.m.wikipedia.org/wiki/Geopolitical_ontology

This kindoff applies and moreover we can link the entry to dbpedia (at least its country) and get richer data 

But I'm not completely sure that's the way to do it since region and super region is implied by the combination of city and country. I.e. we can just join the results from a query for our initiative and a query for the region of a specific city/country from some geo-tripple store

**Comment by ColmMassey** [comment]
https://schema.org/Continent
https://schema.org/PostalAddress
http://www.healthdata.org/sites/default/files/files/Projects/GBD/GBDRegions_countries.pdf

**Comment by ColmMassey** [comment]
Shifted Region/Super Region description to new Issue.
