### ISSUE TITLE
Address ICA geo data errors

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/open-data#23]
There are several large data errors (in in WRONG COUNTRY!) with the following ICA members data. We should evaluate if they are because of the geocoder we are using, or some other source of errors.

Cooperativa de Servicios Múltiples Profesionales, R.L. 
Moshi Co-operative University (MoCU) 
Oromia Coffee Farmers Co-operative Union (OCFCU) Ltd. 
Federación de Cajas Populares ALIANZA SC de RL de CV 
Tanzania Federation of Co-operatives Ltd. (TFC) 
Department of Agricultural Marketing and Cooperatives (DAMC)
Cooperativa De Credito Para Os Funcionários Da Presidência (COOCREFP)

**Comment by ColmMassey** [comment]
See also https://github.com/SolidarityEconomyAssociation/dotcoop-project/issues/2

**Comment by dtmakm27** [comment]
This is directly related with https://github.com/SolidarityEconomyAssociation/open-data/issues/28

Let's see how it goes after we implement the new geocoder
