### ISSUE TITLE
Ensure development and production deployments are not intermingled

### ISSUE THREAD

**Issue by wu-lee** [SolidarityEconomyAssociation/open-data#26]
Some development sea-map deployments are using the production triplestore server for graphs. Ensure dev data goes on dev severs, production on production.

**Comment by ColmMassey** [comment]
Address this Issue should fix https://github.com/SolidarityEconomyAssociation/open-data/issues/24

**Comment by wu-lee** [comment]
I think this can be closed, following work in the various datasets in open-data, and corresponding changes in each of the current 6 sea-map websites (`dotcoop`, `coops-uk`, `ica`, `mutual-aid`, `oxford` and `newbridge`). Links on development data should not take you over to production data and vice versa.

One caveat: on lod.coop this has been solved allowing the same code to cater to both production and development URIs. The webserver supplies the context (a base URL to use), and the lod.coop redirection behaves accordingly. This avoids having two branches with essentially the same (but slightly different) changes, which is awkward and error prone to maintain.

This webserver context is configured when it is deployed, using the ansible scripts in https://github.com/SolidarityEconomyAssociation/technology-and-infrastructure

However, this is not solved on the sea-map websites such as oxford-playground etc. So they *do* need two parallel branches with slightly different URIs. @dtmakm27 beware!

I do think I know how to solve this: the sea-map code should have the right context supplied by the webserver, in the same way that it is for lod.coop. This requires altering get_dataset.php and probably the javascript code/config. Work to be followed up in another ticket.

**Comment by ColmMassey** [comment]
> I do think I know how to solve this: the sea-map code should have the right context supplied by the webserver, in the same way that it is for lod.coop. This requires altering get_dataset.php and probably the javascript code/config. Work to be followed up in another ticket.

Can you put this in another ticket before we close this @wu-lee ?

**Comment by wu-lee** [comment]
I've written something in https://github.com/SolidarityEconomyAssociation/sea-map/issues/76

**Comment by ColmMassey** [comment]
The oxford dev map is still intertwingled.
 see https://github.com/SolidarityEconomyAssociation/open-data/issues/47
