### ISSUE TITLE
Loading Notifications

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/open-data#3]

**Comment by ColmMassey** [comment]
We are now displaying a loading circle when we first open the sea-map. The requirement for this emerged when we had multiple databases available and we were toggling between them. It would be good to see how this looks for a multi-source instance before closing.

**Comment by ColmMassey** [comment]
When the map is an iframe in only part of the screen the position of the load circle is wrong. See dev.oxford or dev.newbridge...

**Comment by dtmakm27** [comment]
does not work for two datasets correctly

**Comment by wu-lee** [comment]
The loading animation now works for multiple datasets adequately. When loading multiple datasets it only reports one dataset, however. See https://github.com/SolidarityEconomyAssociation/sea-map/issues/103

I think this issue can be closed, unless that point needs addressing.
