### ISSUE TITLE
geo duplicates bug in data found

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/open-data#4]
lookup sostre in https://data1.solidarityeconomy.coop/dotcooptestNewData/index.html

**Comment by dtmakm27** [comment]
This is a bug with the API we are using 

e.g.: 
c/casp 43,barcelona,,8010 and "Casp 43, baixos",Barcelona,B,8010,Spain return different locations

try it out at https://opencagedata.com/demo


To solve this we will need a more accurate geoencoder

**Comment by ColmMassey** [comment]
Dropping from the sprint.

**Comment by ColmMassey** [comment]
This should grow into a review of geo services quality in general.
