### ISSUE TITLE
Hypen in postcode throwing geo-coder

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/open-data#43]
At a glance, what do you think is the source of the Calverts Geoloc error here. I guess it might have something to do with the hyphen in the postcode?
There are several other Calverts registrations which worked fine and they had no hypen in postcode.
For UK addresses, it might be worth replacing hyphens with spaces. I wonder if we get a low confidence could we drop back to the OS positioning?
![image](https://user-images.githubusercontent.com/1162642/89272093-8c14b700-d635-11ea-8c30-cc8f631124d0.png)

**Comment by dtmakm27** [comment]
Ah Nice, thanks for the heads up, we should definitely clear them of hyphens or other weird symbols ( !@#$%^&*()_+ ..etc)
(BTW, on this screen you are shown the original address, not the resulting address from the geocoding)

will clear the fields when geocoding, in the latest drop and post an update here @ColmMassey

**Comment by dtmakm27** [comment]
@ColmMassey 

added it, seems to have a better effect
Updated dotcoop map should be ready in about half an hour
