### ISSUE TITLE
dotcoop download link is not correct / not functioning

### ISSUE THREAD

**Issue by wu-lee** [SolidarityEconomyAssociation/open-data#45]
The autobuilder has been failing to download (or even check) the dotcoop data. cron job notifications look like this:

```
PROCESSING dotcoop...
invoking command: download
undefined method `strip' for nil:NilClass
head https://icassstore.blob.core.windows.net/directory-export/export?REDACTED
'downloader' command in current directory failed
```

The link is configured in `dotcoop/staging.conf` for `prod-0`, and `dotcoop/default.conf` for `dev-0`. `sea-0` does not yet run the branch which has dotcoop included in autobuilds.

Checking the link manually seems to get a 403 authentication error, whatever server I try it from:

```
HTTP request sent, awaiting response... 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
2020-09-04 16:07:32 ERROR 403: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature..
```

So possibly:
- the authorisation has been revoked
- the servers are blacklisted, possibly due to rate limiting

We need to check with DotCoop what URL we should be using.

**Comment by wu-lee** [comment]
@dtmakm27 - I think you have the contact for whoever in DotCoop deals with this?

**Comment by dtmakm27** [comment]
sent on discord

**Comment by wu-lee** [comment]
Ok, these URLs are now committed and pushed to the `dev` branch. Each server (`sea-0`, `dev-0`, and `prod-0`) has its own URL. These are recorded in `production.conf`, `default.conf` and `staging.conf` under `dotcoop/` respectively.

Monitoring the cron job emails, I can see that these are working, so closing this issue.

**Comment by ColmMassey** [comment]
Has this been addressed @wu-lee ?

**Comment by wu-lee** [comment]
If you mean the original ticket - yes.

If you mean the recent issue with the dotcoop URLs not downloading the latest data (incl. `attunement.coop`), then also yes. Jonathan has sent working URLs for both prod-1 and dev-1 and they've both rebuilt to show `attunement.coop`.
