### ISSUE TITLE
dev.oxford.solidarityeconomy.coop not getting correct data

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/open-data#47]
https://dev.oxford.solidarityeconomy.coop

is only displaying 9 inititiatives.

https://dev.oxford.solidarityeconomy.coop/configuration/oxford/query.rq
suggests it is getting the data from 
https://lod.coop/sea-lod/oxford
which doesn't seem right. 

Putting this in a browser redirects to https://prod.data.solidarityeconomy.coop/sea-lod/oxford.html which is not populated.

**Comment by ColmMassey** [comment]
However following the link in the about panel it says the data is from

https://prod.data.solidarityeconomy.coop/sea-lod/oxford/index.html

which has good data there, but is on the production server.

**Comment by wu-lee** [comment]
I see what you mean - I'll confer with Dean when he's available and try and sort this out.

**Comment by ColmMassey** [comment]
https://dev.oxford.solidarityeconomy.coop/configuration/oxford/query.rq
now suggests its getting the data correctly from
https://dev.lod.coop/sea-lod/oxford/

About panel points to https://dev.lod.coop/sea-lod/oxford/ which redirects to 

https://dev.data.solidarityeconomy.coop/sea-lod/oxford/index.html

and I can see over 60 inititatives.  :-)
