### ISSUE TITLE
Automate mutual aid rebuild

### ISSUE THREAD

**Issue by wu-lee** [SolidarityEconomyAssociation/open-data#49]
Rebuild data based on a HEAD query ETAG header, as for Dotcoop.

May also require work on the Ruby scripts generating ICA data...

**Comment by wu-lee** [comment]
Mutual Aid data is available here: https://mutualaid.wiki/api/group/get

(See https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/216#issuecomment-640817138)

**Comment by wu-lee** [comment]
Hmm, I see the URL does not provide an ETAG header.

```
nick@mie-goreng:~$ wget -S https://mutualaid.wiki/api/group/get
--2020-09-30 17:25:49--  https://mutualaid.wiki/api/group/get
Resolving mutualaid.wiki (mutualaid.wiki)... 157.230.103.136, 167.99.129.42
Connecting to mutualaid.wiki (mutualaid.wiki)|157.230.103.136|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Access-Control-Allow-Origin: *
  Content-Type: application/json
  Date: Wed, 30 Sep 2020 16:25:50 GMT
  Via: 1.1 eb1a8c1b1275e33a016e623478052111.cloudfront.net (CloudFront)
  X-Amz-Apigw-Id: TsCuIEgMrPEFmBg=
  X-Amz-Cf-Id: _hGNkiDdda8k2yVSvBFKpOacSJiYn5jMXM9U81zsn2qhjevTNzrJdA==
  X-Amz-Cf-Pop: FRA2-C2
  X-Amzn-Requestid: 4a0c4275-a5b2-45e0-a105-fb9ae95843cd
  X-Amzn-Trace-Id: Root=1-5f74b18d-1d1da9395726bcd757cb9f8a;Sampled=0
  X-Cache: Miss from cloudfront
  Age: 1
  Transfer-Encoding: chunked
  Connection: keep-alive
  Server: Netlify
  X-NF-Request-ID: 0a42036a-14d6-4116-8222-500eebd0b63d-22557121
Length: unspecified [application/json]
Saving to: ‘get’

get                                                                    2.29M  1.71MB/s    in 1.3s    
```

**Comment by ColmMassey** [comment]
I have introduced you to someone on email.

**Comment by ColmMassey** [comment]
Sounds like a bit of work. I'd lower its priority and put it back in the stack.

**Comment by wu-lee** [comment]
Ok, I'll post any information Julian comes back with about implementing an ETAG header here in the mean time.

Mutual Aid builds take an extremely long time, so they won't fit in with the 10 minute polling scheme we use for Oxford/Newbridge very well, unless we think and take steps there too.

**Comment by ColmMassey** [comment]
There is less of a case for fast updates here. I think we will probably always have cases where we can't tell when the data has been updated, and where rebuild time is slow, so perhaps we need a daily rebuild list. Can you create a ticket for doing that? I'll prioritise it later. I think it shouldn't be that slow, as I thought the users provided their own lat lons, so we didn't need to do geocoding? @dtmakm27

**Comment by wu-lee** [comment]
Just to update the issue: Julian says they may implement a caching step, which could get us the ETAG header (or an equivalent) we need. Says he'll get back to us when he's got news.

**Comment by dtmakm27** [comment]
>I'll prioritise it later. I think it shouldn't be that slow, as I thought the users provided their own lat lons, so we didn't need to do geocoding?

It doesn't pass them through the geocoder? 
Why ask , do we have faulty data?(if it's about the speed of generating the data, geocoding is fast, since it's getting cached)

**Comment by ColmMassey** [comment]
how long does it take to build MA data now?

**Comment by wu-lee** [comment]
Julian's colleague Dan has gotten back and says an ETAG header of sorts is implemented. However, I can only get it to work in a browser, not in `wget` nor (more to the point) in the open-data `seod` command. Suspect the server might be excluding non-browser agents...?  Needs more investigation.

**Comment by wu-lee** [comment]
Have discovered that their API seems not to support an HTTP HEAD request, which is how we check the ETAG header without downloading the content. Possibly unimplemented, possibly a permissions problem. Have sent an email to Dan asking if this could be investigated.

**Comment by wu-lee** [comment]
> how long does it take to build MA data now?

Just timing it, but many tens of minutes - as mentioned the Co-ops UK build took nearly 5 hours.

**Comment by wu-lee** [comment]
So Dan from Mutual Aid wiki has enabled the HTTP HEAD request in the API, and the ETAG header check now works.

Therefore I've merged in the `mutual-aid-auto-rebuild` branch to `dev`, and pushed it, which means that the mutual aid data should be rebuilt every 10 minutes, or when the data changes, whichever comes last.

We can watch the timestamps here, which should change presently:

https://prod.data.solidarityeconomy.coop/mutual-aid/meta.json

Currently:
```
{
  "timestamp": "2020-09-01 01:28:31 UTC",
  "commit_id": "6f6d26a89dcdd28ae37e6136b7062e1511ec892b",
  "standard_data_hash": "1384a25f83f52dcbda3564af0a420bc0081eb6a6",
  "doc_hash": "74650b3567f562c774d662462da273b7333e0428",
  "user": "nick",
  "host": "mie-goreng"
}
```
And here:

https://dev.data.solidarityeconomy.coop/mutual-aid/meta.json

Currently:
```
{
  "timestamp": "2020-10-01 13:27:54 UTC",
  "commit_id": "3f14ab5a670f98653bdcfc12e40719ea18816148",
  "standard_data_hash": "f189ca48053143c00b924b794b1561432b2a15f1",
  "doc_hash": "2bf88770be38c665c6893def723c55b300e5c9b9",
  "user": "nick",
  "host": "mie-goreng"
}
```

**Comment by wu-lee** [comment]
Running on my desktop, Mutual Aid data takes 50 minutes to run `seod generate`, i.e. the RDF generation.
```
real	129m10.243s
user	79m50.883s
sys	49m14.080s
```

**Comment by ColmMassey** [comment]
How would I verify this? Can I do it before @dtmakm27 has finished the cache updating fix we discussed yesterday? Is there somewhere I can tell what the latest updates are from the MutualAid wiki site, so I can confirm they are getting through to our map?

**Comment by wu-lee** [comment]
Well - I guess you need to know a) when the original data was updated, and b) when our data was updated.

For a) when the data was updated: I can't see any indication on Mutual Aid's website which shows this.

The only way I know of is to check that the ETAG header has changed. Unfortunately there is no "Last Changed" field, they've not implemented that, so if you don't have a record of the old ETAG, AFAIK there *is* no way to tell if or when it last changed!

The way I check the ETAG header is like this, as a shell command. See above for an example of the output.

    wget --method=HEAD -S https://mutualaid.wiki/api/group/get

You can just open the URL in the browser of course, although it does a full download. In Firefox, at least, it seems to download as a JSON document in the browser, and there's a tab "Headers" which contains the information as above.

The `open-data` downloader code knows how to save a copy of the ETAG header to compare with. So you can also log onto `dev-0` and check the date on downloaded file and the cached ETAG header, which will have the date when it noticed and downloaded the new data:

```
root@dev-0:~# ll /home/seopendata/working/mutual-aid/original-data/original.json
-rw-rw-r-- 1 seopendata seopendata 2401650 Oct 13 14:11 /home/seopendata/working/mutual-aid/original-data/original.json

root@dev-0:~# echo $(< /home/seopendata/working/mutual-aid/original-data/original.json.etag )
3785e73a3103e8a7f63af8bd8256dd06
```

As for b) - when our data was updated: look at the metadata uploaded with the data (as mentioned above):

https://dev.data.solidarityeconomy.coop/mutual-aid/meta.json

https://prod.data.solidarityeconomy.coop/mutual-aid/meta.json

**Comment by wu-lee** [comment]
For the record, I asked via email if there is a way to see when the data last changed. Dan said:

> That isn’t something we are currently tracking. But your always free to submit pull request.

**Comment by ColmMassey** [comment]
For clarity, as I think it may have been missed. 

>For my test I wanted to know WHAT the last addition/change made was, so I can manually validate the the new address/group has rippled through the system. 

I am not interested in when.

**Comment by wu-lee** [comment]
Ah - ok. I don't think there's a simple way for you to tell what the last change was, as it stands.  The wiki doesn't show you this, as far as I can tell. I don't know if their API supports this? It's hard to tell because there's no documentation I know of, so it boils down to reading the code, which uses a framework I'm not familiar with.  My impression is the API is minimal and designed to support what the map needs only.

The data records have a `last_changed` field. So in principle you could filter on that, but you'd need something to do that - a spreadsheet, or a bit of javascript.

I see that Firefox has a JSON viewer which is on by default now so it appears if you open the mutual aid data endpoint in the browser. This helps a little, but the filter field is very basic: essentially it's just a search box, so it will filter the elements of the JSON array based on a match anywhere, in keys or values. So you can't look for changes after a certain date, for example, but you can for example filter on a date string fragment like `2020-10` and find changes in October 2020.

I suspect various browser plug-ins would offer more sophisticated filtering methods, but I am not familiar with any of them.

There's also probably a way of doing it in the debug console, I'll see if I can find something straightforward.

**Comment by wu-lee** [comment]
This is how I'd do it, personally. (In Firefox, something similar should work in Chrome.) It may or may not be to your taste.

1. open https://mutualaid.wiki/
2. press F12 to open the debug console (make sure the 'console' tab is selected - you should see a command line)
3. paste the following function definition into the command line: `query = async (q) => (await (await fetch('/api/group/get')).json()).filter(q)`
4. make queries on record fields, such as this: `await query(d => d.updated_at > '2020-10')` (which queries for records with the `updated_at` field, which is text, sorting after `2020-10`)
5. click on the triangular drop-down icons to expand the elements of the resulting data structure to view the contents
![image](https://user-images.githubusercontent.com/67825/96581475-c6573180-12d1-11eb-9123-01b824113531.png)

**Comment by ColmMassey** [comment]
>press F12

That's 'Enable Flight Mode' for me. ;-)

When I follow these instructions I see the same data as in your image.

But I note that these are the same as the first 3 elements in the main view 

![Untitled](https://user-images.githubusercontent.com/1162642/96586431-ea6a4100-12d8-11eb-9172-5d207d8f2c4b.png)
 
in https://mutualaid.wiki/map

**Comment by wu-lee** [comment]
> That's 'Enable Flight Mode' for me. ;-)

Also, I now have all your bank log-in details.

**Comment by ColmMassey** [comment]
> Also, I now have all your bank log-in details.

It did warn me, but for some reason I trust you. Is that back door now closed to anyone else?

**Comment by ColmMassey** [comment]
Seems to be updating. :-)
