### ISSUE TITLE
New use of base_membership_type causing conflicts.

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/open-data#50]
Copide from https://github.com/SolidarityEconomyAssociation/ica-project/issues/3#issuecomment-705492878

I see there's a new standard CSV schema field with ID :base_membership_type. I noticed this when integrating my code - I have a merge conflict. This has some consequences I want to share, and raises a couple of questions.

The reason I noticed: I've de-duplicated the Oxford and Newbridge converter code, so that I don't have to duplicate it a third time when creating Mersey Green.

Earlier I saw that a new field :qualifiers was added to the standard schema. It wasn't being handled in Oxford/Newbridge. This is possible because of the older conversion code uses a class written by Matt called SeOpenData::CSV::Standard::V1, and the newer code use SeOpenData::CSV::Schema (shared code) and SeOpenData::CSV::Schemas (specific cases) to define the fields.

I've fixed it - for now I've added support for the :qualifiers field for Oxford/Newbridge by just inserting a blank field. @dtmakm27 - I hope that's the right thing to do?

I've also marked SeOpenData::CSV::Standard::V1 deprecated, and it now delegates to SeOpenData::CSV::Schemas::Latest to get the fields. This was the direct cause of the merge conflict. But main thing is the class should work as it did before, but without the possibility of adding fields in one case but not the other.

Going forward in general: we want to lose this V1 class eventually, and use Schemas.

Now: the new field :base_membership_type. I'll need to add that to the definition in Schemas too, and I think again all I can do is insert a blank field for non-ICA projects. Right @dtmakm27 ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by wu-lee** [comment]
Following our last meeting, I think that oxford, newbridge and mersey all do the right thing by inserting a blank for these fields.  

Looking at co-ops UK, mutual-aid, and dotcoop, they all use the old RowReader class for conversions, so likewise insert blank fields when nothing else is specified.

ICA of course inserts something, because these fields were added specifically for this case.

Therefore I think this issue is resolved.
