### ISSUE TITLE
Reduce noisiness of automatic builds

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/open-data#53]
Currently the open-data builds send a long email every 10 minutes. This is important for debugging, but is usually just an enormous amount of spam. We should slim it down to emails only when there is an error, and divert the bulk into rotated log files.

**Comment by ColmMassey** [comment]
Has this been addressed? I think it just hasn't been pushed to prod yet.

**Comment by wu-lee** [comment]
You may have noticed the email to WebArchitects, one of the problems is that emails from the server are being blocked due ultimately to the server's low reputation as a mail source, I am investigating ways of routing mail via a server that has a good reputation.

**Comment by wu-lee** [comment]
This should be resolved by https://github.com/SolidarityEconomyAssociation/technology-and-infrastructure/issues/60 when prod-0 is superceded by a prod-1.  (It's resolved now dev-0 is superceded dev-1)

**Comment by wu-lee** [comment]
Oh, although we do need to route the mail in a more permanent way - currently routed via my personal mailserver. For the medium term I recommend we open a mailgun pay-as-you-go account, later maybe set our own mail infrastructure up:

https://www.mailgun.com/pricing/

**Comment by wu-lee** [comment]
The new production server `prod-1` is deployed and handling the builds, and the newer OS means the quieter notification system works properly.  There should only be notification mails sent on failure.

We do still need to find a more permanent way to send mail, have created an issue for that. (https://github.com/SolidarityEconomyAssociation/technology-and-infrastructure/issues/66)

**Comment by ColmMassey** [comment]
Nice. :-)

**Comment by ColmMassey** [comment]
Can you induce an error and see if I get an email?

**Comment by wu-lee** [comment]
You should have had a few already, during the change-over last week,  However I'll see if I can induce another.

**Comment by wu-lee** [comment]
Ok, there was a problem with prod-1, but the build on prod-1 is now reporting failures correctly. 

It was using the `master` branch of `open-data`, which had a build script which was written prior to the new email notification feature. This script didn't return a failure code, ever, so no failures were reported.

I've now adapted the `dev` branch build script and added it to prod-1's own branch, so it will check and return the right code, meaning the notifications get sent if any step fails.

An example notification is pasted below. This notification was induced by deliberately breaking the build, but it's now unbroken and should go quiet again. (The recent error notifications you may have seen from dev-1 are also the result of my deliberately breaking, in this case it by moving the ESSGLOBAL vocab definitions temporarily.)

The main things to note are the "From" header (showing which server sent this), and the penultimate line, which shows which datasets failed:

    FINISHING with 6 failed: oxford newbridge mersey-green deep-adaptation dotcoop covid-mutual-aid

This allows me (or another with access) to go back and comb through the log output for the se_open_data service at the times shown, and look for the cause, using `journalctl`:

    journalctl -S <time to start listing> -u se_open_data

But in this case, it's visible in the email, on the lines with a '!' prefix (these are how the build script marks stderr output from the build jobs, so typically errors):

    seod: command not found


The example notification email:
```
Subject:     FAILED (exit-code/exited): se_open_data.service
Date:     Fri, 12 Nov 2021 15:00:33 +0000 (UTC)
From:     Solidarity Economy Open Data <seopendata@prod-1.solidarityeconomy.coop>
To:     REDACTED

● se_open_data.service - Rebuilds the datasets in /home/seopendata/working
     Loaded: loaded (/etc/systemd/system/se_open_data.service; disabled; vendor preset: enabled)
     Active: deactivating (stop-post) (Result: exit-code) since Fri 2021-11-12 15:00:33 UTC; 24ms ago
TriggeredBy: ● se_open_data.timer
    Process: 1051579 ExecStart=/home/seopendata/sync-and-run (code=exited, status=1/FAILURE)
   Main PID: 1051579 (code=exited, status=1/FAILURE); Control PID: 1051648 (post-sync)
      Tasks: 3 (limit: 2339)
     Memory: 2.8M
     CGroup: /system.slice/se_open_data.service
             ├─1051648 /bin/bash /home/seopendata/post-sync se_open_data.service
             ├─1051649 systemctl status se_open_data.service
             └─1051650 mail -s FAILED (exit-code/exited): se_open_data.service nick@noodlefactory.co.uk colm@solidarityeconomy.coop

Nov 12 15:00:33 prod-1.solidarityeconomy.coop sync-and-run[1051602]: PROCESSING dotcoop...
Nov 12 15:00:33 prod-1.solidarityeconomy.coop sync-and-run[1051633]: [For dotcoop: seod download]
Nov 12 15:00:33 prod-1.solidarityeconomy.coop sync-and-run[1051635]:     ! /home/seopendata/working/tools/deploy/cronjob: line 20: seod: command not found
Nov 12 15:00:33 prod-1.solidarityeconomy.coop sync-and-run[1051602]: FAILED dotcoop (return code 127)
Nov 12 15:00:33 prod-1.solidarityeconomy.coop sync-and-run[1051602]: PROCESSING covid-mutual-aid...
Nov 12 15:00:33 prod-1.solidarityeconomy.coop sync-and-run[1051640]: [For covid-mutual-aid: seod download]
Nov 12 15:00:33 prod-1.solidarityeconomy.coop sync-and-run[1051642]:     ! /home/seopendata/working/tools/deploy/cronjob: line 20: seod: command not found
Nov 12 15:00:33 prod-1.solidarityeconomy.coop sync-and-run[1051602]: FAILED covid-mutual-aid (return code 127)
Nov 12 15:00:33 prod-1.solidarityeconomy.coop sync-and-run[1051602]: FINISHING with 6 failed: oxford newbridge mersey-green deep-adaptation dotcoop covid-mutual-aid
Nov 12 15:00:33 prod-1.solidarityeconomy.coop sync-and-run[1051579]: FAILED (0): /home/seopendata/working/tools/deploy/cronjob
```

**Comment by ColmMassey** [comment]
I confirm I got 3 error messages around 3 today and then they stopped.
