### ISSUE TITLE
Test building from Nextcloud

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/open-data#58]
Test if you can access this file on our cloudserver to build a small graph?

https://nextcloud.solidarityeconomy.coop/index.php/s/YDctt5nbP4e7Rx7

**Comment by ColmMassey** [comment]
>The direct download link on the page is identical to the above URL, so not a download shortcut.

It just seems to add _/download_ to the url

**Comment by ColmMassey** [comment]
>I don't seem to have access to try this, but you could try giving me a public share link for a .csv file instead of an .ods file?

Ideally it is an ods file, but let's try solving for a csv first. That might be sufficient for now.

https://nextcloud.solidarityeconomy.coop/index.php/s/kQXnTxEDYFTmk8o/download

This is a csv file download link in a new public folder. (We can address byzentine permissions issues after.

**Comment by wu-lee** [comment]
Ok, that link downloads fine (no authentication needed, results in a CSV)

No ETAG/last changed headers however.

**Comment by wu-lee** [comment]
I don't think there's anything more to do here @ColmMassey? On the one hand, we can download CSV, but on the other we can't see when it was changed. So it works so long as you are fine with polling, as for Lime Survey.

I also guess you want a client-editable spreadsheet at the back end?

**Comment by ColmMassey** [comment]
> I don't think there's anything more to do here @ColmMassey? On the one hand, we can download CSV, but on the other we can't see when it was changed. So it works so long as you are fine with polling, as for Lime Survey.

So yes, we can close this. We have a path to use Nextcloud csv files using periodic downloads as with Limesurvey.

**Comment by ColmMassey** [comment]
>I also guess you want a client-editable spreadsheet at the back end?

Yes. In this case, it is someone working for SEA, Jo, so has full Nextcloud access already.
