### ISSUE TITLE
New Limesurvey entry triggers database build and redeploy.

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/open-data#6]
Design an implement a method for triggering database rebuilds after approving new survey entries.

**Comment by ColmMassey** [comment]
Limesurvey
- Enable email notification to a dedicated address for survey administrators, so they know that a new survey entry has been made. 
- Extend the Limesurvey template to include a hidden boolean question indicating if the submission has been approved yet.

Sausage Factory
- Add to [first script] to only use entries with a TRUE Approved entry.
- Periodically, or in response to some other trigger 
  - call Limesurvey to see if there have been any updates since last enquiry
    - request export of survey data
    - move csv file to appropriate location
    - call database build and redeploy

**Comment by ColmMassey** [comment]
What options do we have for a third party, like the person approving new entries for a Limesurvey to trigger a rebuild, so the rebuild is not periodic but on request?

**Comment by wu-lee** [comment]
>     * Enable email notification to a dedicated address for survey administrators, so they know that a new survey entry has been made.

According to Lime Survey's [manua][1] this can be done, and is configured per-survey. We can use the placeholder `{ADMINEMAIL}` to send an email to the currently configured admin, or enter an email explicitly.

[1]: https://manual.limesurvey.org/Notifications_%26_data#Basic_and_detailed_admin_notifications_email

Should I do this, if so:
- for which surveys?
- to which emails?
- are there any other notification settings which we need?

**Comment by ColmMassey** [comment]
> Should I do this, if so:

An email notification is set up for the Newbridge project.

**Comment by wu-lee** [comment]
You seems to be implying I don't need to change anything with respect to notifications. Right?

**Comment by ColmMassey** [comment]
Probably worth a voice call.

**Comment by ColmMassey** [comment]
A quick call at 10 would be great.

**Comment by wu-lee** [comment]
Sorry, kids didn't want to do that so I got caught up in something else. Feeling slightly wild now. Maybe after 2, let's say 2.15 because children.

**Comment by wu-lee** [comment]
I've asked how to tell when there is new survey response data here:

https://forums.limesurvey.org/forum/can-i-do-this-with-limesurvey/122433-how-to-check-if-a-survey-s-has-new-or-modified-responses-programmatically

The answers which might help all seem to require writing a plug-in for limesurvey, but on our current hosting we can't install 3rd party plugins.

One thing which might still work is a notification email, which could be sent to the server running the autobuild code. I can't see these so I don't know exactly what they contain or when they get sent. @ColmMassey - perhaps you could comment on that? Do the modifications we're interested in result in an email notification?

The only other thing seems to be to inspect the web UI and API more carefully looking for hints. The difficulty seems to be that although limesurvey has a response state signifying "completion", modifications after that will not be visible as any state change.

**Comment by ColmMassey** [comment]
> One thing which might still work is a notification email, which could be sent to the server running the autobuild code. I can't see these so I don't know exactly what they contain or when they get sent. @ColmMassey - perhaps you could comment on that? Do the modifications we're interested in result in an email notification?

The notification is sent when a survey has been submitted, but the admin then needs to approve them. So we'd an email sent after that.
