### ISSUE TITLE
Write JSON dictionary creating sparql queries form ESSGlobal VESs

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/open-data#69]
We need to write those sparql queries to generate each of the vocab dictionaries. 

Most will be straight forward, like activities-ICA but the one to generate the vocab for structure-ICA will need to deal with exceptions like the interpretation of the qualifier.

Need to see if we also need some and php cleanup scripts to remove any exxess cruft that is hard to strip using sparql.

**Comment by ColmMassey** [comment]
See https://github.com/SolidarityEconomyAssociation/sea-map/issues/104 and 
https://github.com/SolidarityEconomyAssociation/open-data/issues/68

**Comment by ColmMassey** [comment]
Consider interpreting<https://w3id.solidarityeconomy.coop/essglobal/V2a/standard/qualifiers/q09> as a term in

<https://w3id.solidarityeconomy.coop/essglobal/V2a/standard/structure-ICA>

Consider shortening https://w3id.solidarityeconomy.coop/essglobal/V2a/standard/structure-ICA/activities-ica/ICA20 to ICA20 say.

**Comment by wu-lee** [comment]
Some discussion of this here: https://github.com/SolidarityEconomyAssociation/sea-map/issues/104#issuecomment-777393866
