### ISSUE TITLE
Evaluate National Polygon Service alternative

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/open-data#73]
This blog shows how to link Inspire IDs to land ownership 

https://anna.ps/blog/how-to-use-land-registry-data-to-explore-land-ownership-near-you

Evaluate what it would take for LE to use the (now freely available) Inspire polygons.

**Comment by King-Mob** [comment]
Hansen wrote the service that hosts the polygons for Land Explorer, so I've asked him about using the INSPIRE set. Looks possible, the only annoyance is having to download them by local authority each time.

**Comment by King-Mob** [comment]
For reference, the set appears here: https://use-land-property-data.service.gov.uk/datasets/inspire/download#download
